server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/cine_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

api.tipo-cambio.url=https://open.er-api.com/v6/latest/USD
api.dni.url=https://api.apis.net.pe/v2/reniec/dni
api.dni.token=
